-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 16:01:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdencuesta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdencuesta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdencuesta` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bdencuesta` ;

-- -----------------------------------------------------
-- Table `bdencuesta`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `bdencuesta`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `bdencuesta`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bdencuesta`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bdencuesta`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdencuesta`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `bdencuesta`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdencuesta`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `bdencuesta`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdencuesta`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_nacionalidad` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 218
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_pais` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 249
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_capituloi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_capituloi` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `edad` INT NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `viaja_con` VARCHAR(1) NOT NULL,
  `viaja_con_otro` VARCHAR(100) NULL DEFAULT NULL,
  `numero_personas` INT NOT NULL,
  `user_id` INT NOT NULL,
  `nacionalidad_id` BIGINT NULL DEFAULT NULL,
  `pais_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `encuesta_capituloi_nacionalidad_id_b8165b1a_fk_encuesta_` (`nacionalidad_id` ASC) VISIBLE,
  INDEX `encuesta_capituloi_pais_id_9a72d7ff_fk_encuesta_pais_id` (`pais_id` ASC) VISIBLE,
  INDEX `encuesta_capituloi_user_id_730f1425_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `encuesta_capituloi_nacionalidad_id_b8165b1a_fk_encuesta_`
    FOREIGN KEY (`nacionalidad_id`)
    REFERENCES `bdencuesta`.`encuesta_nacionalidad` (`id`),
  CONSTRAINT `encuesta_capituloi_pais_id_9a72d7ff_fk_encuesta_pais_id`
    FOREIGN KEY (`pais_id`)
    REFERENCES `bdencuesta`.`encuesta_pais` (`id`),
  CONSTRAINT `encuesta_capituloi_user_id_730f1425_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdencuesta`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_capituloii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_capituloii` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `motivo_viaje` VARCHAR(2) NOT NULL,
  `motivo_viaje_otro` VARCHAR(100) NULL DEFAULT NULL,
  `organizacion_viaje_otro` VARCHAR(100) NULL DEFAULT NULL,
  `transporte_interno_otro` VARCHAR(100) NULL DEFAULT NULL,
  `otro_servicio` VARCHAR(100) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `encuesta_capituloii_user_id_8b5bb76c_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `encuesta_capituloii_user_id_8b5bb76c_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdencuesta`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_organizacionviaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_organizacionviaje` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_capituloii_organizacion_viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_capituloii_organizacion_viaje` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `capituloii_id` BIGINT NOT NULL,
  `organizacionviaje_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `encuesta_capituloii_orga_capituloii_id_organizaci_bdc5d5ab_uniq` (`capituloii_id` ASC, `organizacionviaje_id` ASC) VISIBLE,
  INDEX `encuesta_capituloii__organizacionviaje_id_03df9ae0_fk_encuesta_` (`organizacionviaje_id` ASC) VISIBLE,
  CONSTRAINT `encuesta_capituloii__capituloii_id_cbe6acb0_fk_encuesta_`
    FOREIGN KEY (`capituloii_id`)
    REFERENCES `bdencuesta`.`encuesta_capituloii` (`id`),
  CONSTRAINT `encuesta_capituloii__organizacionviaje_id_03df9ae0_fk_encuesta_`
    FOREIGN KEY (`organizacionviaje_id`)
    REFERENCES `bdencuesta`.`encuesta_organizacionviaje` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_serviciospaquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_serviciospaquete` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_capituloii_servicios_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_capituloii_servicios_paquete` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `capituloii_id` BIGINT NOT NULL,
  `serviciospaquete_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `encuesta_capituloii_serv_capituloii_id_serviciosp_82c81dd6_uniq` (`capituloii_id` ASC, `serviciospaquete_id` ASC) VISIBLE,
  INDEX `encuesta_capituloii__serviciospaquete_id_bc5f3f8a_fk_encuesta_` (`serviciospaquete_id` ASC) VISIBLE,
  CONSTRAINT `encuesta_capituloii__capituloii_id_b581132c_fk_encuesta_`
    FOREIGN KEY (`capituloii_id`)
    REFERENCES `bdencuesta`.`encuesta_capituloii` (`id`),
  CONSTRAINT `encuesta_capituloii__serviciospaquete_id_bc5f3f8a_fk_encuesta_`
    FOREIGN KEY (`serviciospaquete_id`)
    REFERENCES `bdencuesta`.`encuesta_serviciospaquete` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_moneda` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo_divisa` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 269
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_capituloiii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_capituloiii` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `gasto_paquete_turistico` TINYINT(1) NOT NULL,
  `valor_paquete_usted` DECIMAL(10,2) NOT NULL,
  `valor_paquete_terceros_no_grupo` DECIMAL(10,2) NOT NULL,
  `valor_paquete_terceros_si_grupo` DECIMAL(10,2) NOT NULL,
  `personas_paquete` INT NOT NULL,
  `gasto_transporte_internacional` TINYINT(1) NOT NULL,
  `valor_transporte_usted` DECIMAL(10,2) NOT NULL,
  `valor_transporte_terceros_no_grupo` DECIMAL(10,2) NOT NULL,
  `valor_transporte_terceros_si_grupo` DECIMAL(10,2) NOT NULL,
  `personas_transporte` INT NOT NULL,
  `user_id` INT NOT NULL,
  `moneda_paquete_terceros_no_grupo_id` BIGINT NOT NULL,
  `moneda_paquete_terceros_si_grupo_id` BIGINT NOT NULL,
  `moneda_paquete_usted_id` BIGINT NOT NULL,
  `moneda_transporte_terceros_no_grupo_id` BIGINT NOT NULL,
  `moneda_transporte_terceros_si_grupo_id` BIGINT NOT NULL,
  `moneda_transporte_usted_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `encuesta_capituloiii_moneda_paquete_terce_96b1c6b7_fk_encuesta_` (`moneda_paquete_terceros_no_grupo_id` ASC) VISIBLE,
  INDEX `encuesta_capituloiii_moneda_paquete_terce_3ac5e067_fk_encuesta_` (`moneda_paquete_terceros_si_grupo_id` ASC) VISIBLE,
  INDEX `encuesta_capituloiii_moneda_paquete_usted_98464b16_fk_encuesta_` (`moneda_paquete_usted_id` ASC) VISIBLE,
  INDEX `encuesta_capituloiii_moneda_transporte_te_f7c5578e_fk_encuesta_` (`moneda_transporte_terceros_no_grupo_id` ASC) VISIBLE,
  INDEX `encuesta_capituloiii_moneda_transporte_te_f76b3acc_fk_encuesta_` (`moneda_transporte_terceros_si_grupo_id` ASC) VISIBLE,
  INDEX `encuesta_capituloiii_moneda_transporte_us_8ca4fa1b_fk_encuesta_` (`moneda_transporte_usted_id` ASC) VISIBLE,
  INDEX `encuesta_capituloiii_user_id_0e60c41e_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `encuesta_capituloiii_moneda_paquete_terce_3ac5e067_fk_encuesta_`
    FOREIGN KEY (`moneda_paquete_terceros_si_grupo_id`)
    REFERENCES `bdencuesta`.`encuesta_moneda` (`id`),
  CONSTRAINT `encuesta_capituloiii_moneda_paquete_terce_96b1c6b7_fk_encuesta_`
    FOREIGN KEY (`moneda_paquete_terceros_no_grupo_id`)
    REFERENCES `bdencuesta`.`encuesta_moneda` (`id`),
  CONSTRAINT `encuesta_capituloiii_moneda_paquete_usted_98464b16_fk_encuesta_`
    FOREIGN KEY (`moneda_paquete_usted_id`)
    REFERENCES `bdencuesta`.`encuesta_moneda` (`id`),
  CONSTRAINT `encuesta_capituloiii_moneda_transporte_te_f76b3acc_fk_encuesta_`
    FOREIGN KEY (`moneda_transporte_terceros_si_grupo_id`)
    REFERENCES `bdencuesta`.`encuesta_moneda` (`id`),
  CONSTRAINT `encuesta_capituloiii_moneda_transporte_te_f7c5578e_fk_encuesta_`
    FOREIGN KEY (`moneda_transporte_terceros_no_grupo_id`)
    REFERENCES `bdencuesta`.`encuesta_moneda` (`id`),
  CONSTRAINT `encuesta_capituloiii_moneda_transporte_us_8ca4fa1b_fk_encuesta_`
    FOREIGN KEY (`moneda_transporte_usted_id`)
    REFERENCES `bdencuesta`.`encuesta_moneda` (`id`),
  CONSTRAINT `encuesta_capituloiii_user_id_0e60c41e_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdencuesta`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdencuesta`.`encuesta_paisvisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdencuesta`.`encuesta_paisvisita` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `noches_vivienda_propia` INT NOT NULL,
  `noches_hotel` INT NOT NULL,
  `noches_vivienda_familiar_amigos` INT NOT NULL,
  `noches_vivienda_alquiler` INT NOT NULL,
  `noches_otro_tipo_vivienda` INT NOT NULL,
  `capitulo_id` BIGINT NOT NULL,
  `pais_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `encuesta_paisvisita_capitulo_id_c3a891dc_fk_encuesta_` (`capitulo_id` ASC) VISIBLE,
  INDEX `encuesta_paisvisita_pais_id_9d22342d_fk_encuesta_pais_id` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `encuesta_paisvisita_capitulo_id_c3a891dc_fk_encuesta_`
    FOREIGN KEY (`capitulo_id`)
    REFERENCES `bdencuesta`.`encuesta_capituloiii` (`id`),
  CONSTRAINT `encuesta_paisvisita_pais_id_9d22342d_fk_encuesta_pais_id`
    FOREIGN KEY (`pais_id`)
    REFERENCES `bdencuesta`.`encuesta_pais` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
